import maze.obstacles as obs
import maze.maze_solver as mazerun

# variables tracking position and direction
position_x = 0
position_y = 0
directions = ['forward', 'right', 'back', 'left']
current_direction_index = 0
 
# the robot obstacles
rob_obs = []

# area limit vars
min_y, max_y = -200, 200
min_x, max_x = -100, 100


def mazerunner(edge):
    global position_x,position_y,directions,current_direction_index
    
    
    
    mazerun.init_position_x = position_x
    mazerun.init_position_y = position_y
    mazerun.edge = edge
    mazerun.init_direction = directions[current_direction_index]
    mazerun.obstacles = rob_obs

    path = mazerun.mazerunner()
    mazerun.obstacles = []
    mazerun.visited_nodes = []
    return path



def reset_vars():
    """RESET VARS
     ============
     
     - Resets the global variables of the file back to their initial state"""
    
    
    global position_x,position_y,current_direction_index,rob_obs
    position_x,position_y,current_direction_index,rob_obs = 0,0,0,[]


def generate_world_obstacle(world_obstacle):
    """GENERATE WORLD OBSTALCE
      =========================
    - Gets the obstacles generated by the robot.py file and assigns 
    the obstacles to this file and the obstacle file imported by this file"""
    
    
    obs.rob_obstacles = world_obstacle


def show_position(robot_name):
    print(' > '+robot_name+' now at position ('+str(position_x)+','+str(position_y)+').')


def is_position_allowed(new_x, new_y):
    """
    Checks if the new position will still fall within the max area limit
    :param new_x: the new/proposed x position
    :param new_y: the new/proposed y position
    :return: True if allowed, i.e. it falls in the allowed area, else False
    """

    return min_x <= new_x <= max_x and min_y <= new_y <= max_y


def update_position(steps):
    """
    Update the current x and y positions given the current direction, and specific nr of steps
    :param steps:
    :return: True if the position was updated, else False
    """

    global position_x, position_y
    new_x = position_x
    new_y = position_y

    if directions[current_direction_index] == 'forward':
        new_y = new_y + steps
    elif directions[current_direction_index] == 'right':
        new_x = new_x + steps
    elif directions[current_direction_index] == 'back':
        new_y = new_y - steps
    elif directions[current_direction_index] == 'left':
        new_x = new_x - steps

    if is_position_allowed(new_x, new_y) and not obs.is_path_blocked(position_x,position_y,new_x,new_y):
        position_x = new_x
        position_y = new_y
        return True
    elif obs.is_path_blocked(position_x,position_y,new_x,new_y):
        return None
    return False


def do_forward(robot_name, steps):
    """
    Moves the robot forward the number of steps
    :param robot_name:
    :param steps:
    :return: (True, forward output text)
    """
    verify_update_pos = update_position(steps)
    if verify_update_pos:
        return True, ' > '+robot_name+' moved forward by '+str(steps)+' steps.'
    elif verify_update_pos == None:
        return True, ' > '+robot_name+' Sorry, there is an obstacle in the way.'
    else:
        return True, ''+robot_name+': Sorry, I cannot go outside my safe zone.'


def do_back(robot_name, steps):
    """
    Moves the robot forward the number of steps
    :param robot_name:
    :param steps:
    :return: (True, forward output text)
    """
    
    
    verify_update_pos = update_position(-steps)
    if verify_update_pos:
        return True, ' > '+robot_name+' moved back by '+str(steps)+' steps.'
    elif verify_update_pos == None:
        return True, ' > '+robot_name+' Sorry, there is an obstacle in the way.'
    else:
        return True, ''+robot_name+': Sorry, I cannot go outside my safe zone.'


def do_right_turn(robot_name):
    """
    Do a 90 degree turn to the right
    :param robot_name:
    :return: (True, right turn output text)
    """
    
    
    global current_direction_index

    current_direction_index += 1
    if current_direction_index > 3:
        current_direction_index = 0

    return True, ' > '+robot_name+' turned right.'


def do_left_turn(robot_name):
    """
    Do a 90 degree turn to the left
    :param robot_name:
    :return: (True, left turn output text)
    """
    
    
    global current_direction_index

    current_direction_index -= 1
    if current_direction_index < 0:
        current_direction_index = 3

    return True, ' > '+robot_name+' turned left.'


def do_sprint(robot_name, steps):
    """
    Sprints the robot, i.e. let it go forward steps + (steps-1) + (steps-2) + .. + 1 number of steps, in iterations
    :param robot_name:
    :param steps:
    :return: (True, forward output)
    """

    if steps == 1:
        return do_forward(robot_name, 1)
    else:
        (do_next, command_output) = do_forward(robot_name, steps)
        print(command_output)
        return do_sprint(robot_name, steps - 1)